const QUESTIONS = [
  {q:"How many surahs are in the Holy Qur’an?", options:["110","112","114","116"], answer:2, ref:""},
  {q:"Into how many equal parts (juz’) is the Qur’an divided for recitation?", options:["7","15","30","60"], answer:2, ref:""},
  {q:"What is the language of the Qur’an?", options:["Classical Arabic","Syriac","Aramaic","Hebrew"], answer:0, ref:""},
  {q:"Which surah is recited in every rak‘ah of the formal prayer (salat)?", options:["Al-Ikhlas","Al-Fatihah","Al-Kafirun","Al-Nas"], answer:1, ref:""},
  {q:"Which surah is the longest in the Qur’an?", options:["Al-Imran","Al-Baqarah","Al-A‘raf","Al-Nisa"], answer:1, ref:""},
  {q:"Which surah is the shortest in the Qur’an?", options:["Al-Kawthar","Al-‘Asr","Al-Nasr","Al-Qadr"], answer:0, ref:""},
  {q:"Which verses were revealed first to the Holy Prophet Muhammad (sa)?", options:["Al-Fatihah","Al-Qadr","Al-‘Alaq 96:1-5","Al-Mudaththir 74:1-7"], answer:2, ref:""},
  {q:"What title is given to the Prophet Muhammad (sa) in Qur’an 33:40?", options:["Rahmatan lil-‘Alamin","Khatam al-Nabiyyin","Siraj-an Munira","Nabi-yullah"], answer:1, ref:"33:40"},
  {q:"Which surah does not begin with ‘Bismillahir-Rahmanir-Rahim’?", options:["At-Tawbah (9)","Yunus (10)","Hud (11)","Yusuf (12)"], answer:0, ref:""},
  {q:"How many times does the name ‘Muhammad’ appear in the Qur’an?", options:["2","3","4","5"], answer:2, ref:""},
  {q:"In which surah does the name ‘Ahmad’ appear?", options:["Al-Imran","Al-Ahzab","As-Saff","Al-Jumu‘ah"], answer:2, ref:"61:6"},
  {q:"Which surah is named after Mary, the mother of Jesus (as)?", options:["Al-Imran","Maryam","An-Nisa","At-Tahrim"], answer:1, ref:"19"},
  {q:"Which surah is also called Bani Isra’il?", options:["Al-Isra (17)","Al-Ankabut (29)","Al-Qasas (28)","Al-An‘am (6)"], answer:0, ref:"17"},
  {q:"Which surah contains Ayat al-Kursi?", options:["Al-Baqarah 2:255","Al-Imran 3:18","An-Nisa 4:136","Al-A‘raf 7:54"], answer:0, ref:"2:255"},
  {q:"Which surah contains the Verse of Light (Ayat an-Nur)?", options:["Al-Ahzab 33:56","An-Nur 24:35","Al-Mulk 67:1","Ar-Rahman 55:13"], answer:1, ref:"24:35"},
  {q:"Which surah tells the story of the People of the Cave?", options:["Yusuf","Maryam","Al-Kahf","Taha"], answer:2, ref:"18"},
  {q:"In which surah is Dhu’l-Qarnayn mentioned?", options:["Al-Anbiya","Al-Kahf","Yasin","Az-Zukhruf"], answer:1, ref:"18"},
  {q:"Which surah tells the story of Prophet Joseph (Yusuf) in a continuous narrative?", options:["Hud","Yusuf","Yunus","Ibrahim"], answer:1, ref:"12"},
  {q:"Which surah contains the command to face the Ka‘bah (change of qiblah)?", options:["Al-Baqarah 2:144","Al-Imran 3:95","An-Nisa 4:103","Al-Ma’idah 5:6"], answer:0, ref:"2:144"},
  {q:"What is the usual classification of surahs by place of revelation?", options:["Makki and Madani","Eastern and Western","Northern and Southern","First and Last"], answer:0, ref:""},
  {q:"How many Makki and Madani surahs are commonly counted?", options:["90 Makki / 24 Madani","86 Makki / 28 Madani","80 Makki / 34 Madani","70 Makki / 44 Madani"], answer:1, ref:""},
  {q:"Over approximately how many years was the Qur’an revealed?", options:["10","20","23","30"], answer:2, ref:""},
  {q:"Which surah condemns cheating in weights and measures?", options:["Al-Hujurat","Al-Mutaffifin","At-Tin","Al-Ma‘un"], answer:1, ref:"83"},
  {q:"Which surah emphasises time and the human condition in three short verses?", options:["Al-‘Asr","Al-Qadr","Al-Kawthar","Al-Nasr"], answer:0, ref:"103"},
  {q:"Which surah begins with ‘By the Dawn’?", options:["Al-Fajr","Ad-Duha","Ash-Shams","Al-Layl"], answer:0, ref:"89"},
  {q:"Which surah begins with ‘By the bright morning hours’?", options:["Ash-Shams","Ad-Duha","Al-Qadr","Al-Balad"], answer:1, ref:"93"},
  {q:"Which surah contains the repeated refrain ‘Which, then, of the favours of your Lord will you two deny?’", options:["Ar-Rahman","Al-Qamar","Al-Buruj","Ad-Dukhan"], answer:0, ref:"55"},
  {q:"Which surah describes the Battle of the Confederates?", options:["Al-Anfal","At-Taubah","Al-Ahzab","Muhammad"], answer:2, ref:"33"},
  {q:"Which surah narrates the incident of the elephant?", options:["Quraish","Al-Fil","Al-Humazah","Al-‘Adiyat"], answer:1, ref:"105"},
  {q:"Which surah is named after Friday?", options:["Al-Ahzab","As-Saff","Al-Jumu‘ah","Al-Munafiqun"], answer:2, ref:"62"},
  {q:"Which surah is named after ‘the Bee’?", options:["Al-Nahl","An-Naml","Al-‘Ankabut","Al-An‘am"], answer:0, ref:"16"},
  {q:"Which surah is named after ‘the Ant’?", options:["Al-Nahl","An-Naml","Al-‘Ankabut","Al-An‘am"], answer:1, ref:"27"},
  {q:"Which surah is named after ‘the Spider’?", options:["Al-Nahl","An-Naml","Al-‘Ankabut","Al-An‘am"], answer:2, ref:"29"},
  {q:"Which surah is named after ‘the Cattle’?", options:["Al-An‘am","Al-Baqarah","Al-Fil","Al-‘Adiyat"], answer:0, ref:"6"},
  {q:"Which surah is named after ‘the Cow’?", options:["Al-Baqarah","Al-An‘am","Al-Nahl","Al-Qasas"], answer:0, ref:"2"},
  {q:"Which surah begins with the oath ‘By the Pen’?", options:["Al-‘Alaq","Al-Qadr","Al-Qalam","Al-‘Alaq and Al-Qalam"], answer:2, ref:"68:1"},
  {q:"How many surahs begin with disjointed letters (huruf-e-muqatta‘at)?", options:["14","19","29","39"], answer:2, ref:""},
  {q:"Which of these begins with ‘Alif-Lam-Mim’?", options:["Yunus","Yusuf","Maryam","Al-Baqarah"], answer:3, ref:"2:1"},
  {q:"Which surah contains ‘There is no compulsion in religion’?", options:["Al-Baqarah 2:256","An-Nisa 4:171","Al-Mumtahanah 60:8","Al-Kafirun 109:6"], answer:0, ref:"2:256"},
  {q:"Which surah contains the verse promising divine protection of the Qur’an?", options:["Yunus 10:64","Al-Hijr 15:9","An-Nur 24:35","Fussilat 41:42"], answer:1, ref:"15:9"},
  {q:"Which surah explicitly prohibits intoxicants and gambling?", options:["Al-Baqarah 2:219","An-Nisa 4:43","Al-Ma’idah 5:90-91","An-Nur 24:31"], answer:2, ref:"5:90-91"},
  {q:"Which surah details the recipients of Zakat (alms)?", options:["Al-Baqarah 2:177","Al-Ma’idah 5:3","At-Taubah 9:60","Al-Hajj 22:28"], answer:2, ref:"9:60"},
  {q:"Which surah contains: ‘Obey Allah, obey the Messenger, and those in authority among you’?", options:["An-Nisa 4:59","Al-Ahzab 33:36","Al-Imran 3:32","Al-Hujurat 49:14"], answer:0, ref:"4:59"},
  {q:"Which surah speaks of the Night of Decree (Qadr)?", options:["Al-Qadr 97","Ad-Dukhan 44","Both A and B","Al-Fath 48"], answer:2, ref:"97, 44:3"},
  {q:"Which surah mentions that the Qur’an was sent down in Ramadan?", options:["Al-Baqarah 2:185","Al-Imran 3:190","Al-Qadr 97:1","Ad-Dukhan 44:3"], answer:0, ref:"2:185"},
  {q:"Which surah includes the prayer ‘Rabbana atina fid-dunya hasanah…’?", options:["Al-Baqarah 2:201","Al-Imran 3:8","Ibrahim 14:40","Ghafir 40:60"], answer:0, ref:"2:201"},
  {q:"Which surah declares: ‘And We have indeed made the Qur’an easy to remember’?", options:["Al-Qamar 54:17","Al-Rahman 55:13","Al-Haqah 69:40","Al-Mudaththir 74:31"], answer:0, ref:"54:17"},
  {q:"Which surah contains ‘Allah is the Light of the heavens and the earth’?", options:["An-Nur 24:35","Al-Zumar 39:69","Al-Hadid 57:3","Al-Hashr 59:24"], answer:0, ref:"24:35"},
  {q:"Which surah contains the command: ‘And consult them in matters’?", options:["Al-Imran 3:159","Ash-Shura 42:38","Al-Nisa 4:58","Al-Anfal 8:61"], answer:0, ref:"3:159"},
  {q:"Which surah forbids backbiting, mockery and suspicion and declares believers to be brothers?", options:["Al-Nur 24","Al-Ahzab 33","Al-Hujurat 49","Al-Mumtahanah 60"], answer:2, ref:"49:10-12"},
  {q:"Which surah contains: ‘O mankind, We created you from a male and a female…’?", options:["Al-Nisa 4:1","Al-A‘raf 7:26","Al-Hujurat 49:13","Ar-Rum 30:21"], answer:2, ref:"49:13"},
  {q:"Which surah promises the establishment of Khilafat for the believers (Ahmadiyya emphasis)?", options:["Al-Imran 3:104","An-Nur 24:55","Al-Ahzab 33:72","Al-Hashr 59:9"], answer:1, ref:"24:55"},
  {q:"Which surah records Jesus (as) prophesying a Messenger named ‘Ahmad’?", options:["Maryam 19:30","Al-Ma’idah 5:75","As-Saff 61:6","Al-Hadid 57:27"], answer:2, ref:"61:6"},
  {q:"Which surah says: ‘Messiah, Jesus, son of Mary, was only a Messenger of Allah… and His Word… and a spirit from Him’?", options:["Al-Imran 3:45","An-Nisa 4:171","Maryam 19:34","Al-Ma’idah 5:110"], answer:1, ref:"4:171"},
  {q:"Which surah declares ‘They killed him not, nor did they crucify him’ regarding Jesus (as)?", options:["Al-Imran 3:55","An-Nisa 4:157","Al-Ma’idah 5:75","Maryam 19:33"], answer:1, ref:"4:157"},
  {q:"According to Ahmadiyya exegesis, the phrase mutawaffīka in 3:55 most correctly means:", options:["I will raise you bodily to the sky alive","I will cause you to die a natural death","I will make you sleep temporarily","I will hide you from your enemies"], answer:1, ref:"3:55"},
  {q:"Which surah states: ‘And He found you not following a way and made you find guidance’?", options:["Ad-Duha 93","Ash-Sharh 94","Al-‘Alaq 96","At-Tin 95"], answer:0, ref:"93:7"},
  {q:"Which surah ends with ‘From among jinn and men’?", options:["Al-Falaq 113","Al-Nas 114","Al-Ikhlas 112","Al-Kafirun 109"], answer:1, ref:"114:6"},
  {q:"Which surah begins with ‘Say, He is Allah, the One’?", options:["Al-Ikhlas","Al-Falaq","Al-Nas","Al-Kafirun"], answer:0, ref:"112:1"},
  {q:"Which surah begins with ‘Say, I seek refuge with the Lord of the dawn’?", options:["Al-Ikhlas","Al-Falaq","Al-Nas","Al-Kafirun"], answer:1, ref:"113:1"},
  {q:"Which surah begins with ‘Say, O disbelievers’?", options:["Al-Ikhlas","Al-Falaq","Al-Nas","Al-Kafirun"], answer:3, ref:"109:1"},
  {q:"Which surah contains the story of Qarun (Korah)?", options:["Al-Qasas 28","Al-A‘raf 7","Yunus 10","Ghafir 40"], answer:0, ref:"28:76-82"},
  {q:"Which surah contains the slander incident and exoneration verses?", options:["Al-Ahzab 33","An-Nur 24","Al-Mujadilah 58","Al-Nisa 4"], answer:1, ref:"24:11-20"},
  {q:"Which surah commands veiling/modesty for believing women?", options:["An-Nur 24:31","Al-Ahzab 33:59","Both A and B","Al-Mumtahanah 60:12"], answer:2, ref:"24:31; 33:59"},
  {q:"Which surah contains the law of four witnesses for accusations of adultery?", options:["An-Nur 24:4","An-Nisa 4:15","Al-Ma’idah 5:5","Al-Ahzab 33:35"], answer:0, ref:"24:4"},
  {q:"Which surah contains the longest verse of the Qur’an about debt contracts?", options:["Al-Baqarah 2:282","Al-Imran 3:190","An-Nisa 4:176","Al-Ma’idah 5:8"], answer:0, ref:"2:282"},
  {q:"Which surah contains the verse ‘And kill not your children for fear of poverty’?", options:["Al-An‘am 6:151","Al-Isra 17:31","Both A and B","Maryam 19:8"], answer:2, ref:"6:151; 17:31"},
  {q:"Which surah teaches: ‘And be not forgetful of excellence (ihsan) between you’?", options:["Al-Baqarah 2:237","An-Nisa 4:36","An-Nur 24:22","Al-Hashr 59:10"], answer:2, ref:"24:22"},
  {q:"Which surah contains: ‘Allah enjoins justice and the doing of good…’ recited in Friday sermons?", options:["Al-Nahl 16:90","Al-Jumu‘ah 62:9","Al-Hajj 22:41","Al-Ma’idah 5:8"], answer:0, ref:"16:90"},
  {q:"Which surah mentions the she-camel as a divine sign in relation to Thamud?", options:["Hud 11","Ash-Shu‘ara 26","Ash-Shams 91:13","Al-Qamar 54"], answer:2, ref:"91:13"},
  {q:"Which surah declares the prohibition of usury (riba) most explicitly?", options:["Al-Baqarah 2:275-279","Al-Imran 3:130","Both A and B","An-Nisa 4:29"], answer:2, ref:"2:275-279; 3:130"},
  {q:"Which surah says, ‘Prayer is enjoined on the believers at fixed times’?", options:["Al-Baqarah 2:238","An-Nisa 4:103","Al-Isra 17:78","Al-Mu’minun 23:9"], answer:1, ref:"4:103"},
  {q:"Which surah contains the embryonic development description ‘from a drop… a clot…’?", options:["Al-Mu’minun 23:12-14","Al-‘Alaq 96:2","Both A and B","Al-Insan 76:2"], answer:2, ref:"23:12-14; 96:2"},
  {q:"Which surah contains the parable of the two gardens (wealthy man and his companion)?", options:["Al-Kahf 18","Al-Hashr 59","Al-Qalam 68","Al-Rahman 55"], answer:0, ref:"18:32-44"},
  {q:"Which surah includes: ‘Do not say “uff” to them’ regarding parents?", options:["Luqman 31:14","Al-Isra 17:23","Al-Ankabut 29:8","Al-Ahqaf 46:15"], answer:1, ref:"17:23"},
  {q:"Which surah states: ‘And do not commit excess; surely He loves not the excessive’?", options:["Al-Ma’idah 5:87","Al-A‘raf 7:31","Al-Isra 17:26","Al-Furqan 25:67"], answer:1, ref:"7:31"},
  {q:"Which surah commands returning trusts and judging with justice?", options:["An-Nisa 4:58","Al-Ma’idah 5:8","Al-Hajj 22:41","Al-Shura 42:15"], answer:0, ref:"4:58"},
  {q:"Which surah declares: ‘And the male is not like the female’ (spoken by the mother of Mary)?", options:["Al-Imran 3:36","Maryam 19:28","An-Nisa 4:1","Al-Ahzab 33:35"], answer:0, ref:"3:36"},
  {q:"Which surah proclaims: ‘O you who believe! Enter into peace wholly (silmi kaaffah)’?", options:["Al-Baqarah 2:208","Al-Imran 3:102","An-Nisa 4:125","Al-Mujadilah 58:22"], answer:0, ref:"2:208"},
  {q:"Which surah says: ‘And in their wealth was a share for the beggar and the deprived’?", options:["Al-Ma‘arij 70:24-25","Ad-Dhariyat 51:19","Both A and B","Al-Hashr 59:9"], answer:2, ref:"70:24-25; 51:19"},
  {q:"Which surah contains the parable of ‘a good word… like a good tree’?", options:["Ibrahim 14:24-25","Al-Nur 24:35","Al-Baqarah 2:261","Al-Hashr 59:21"], answer:0, ref:"14:24-25"},
  {q:"Which surah warns against saying about Allah what you do not know?", options:["Al-A‘raf 7:33","Al-Baqarah 2:80","Al-Imran 3:94","An-Nahl 16:116"], answer:3, ref:"16:116"},
  {q:"Which surah forbids ridicule, offensive nicknames, spying, and backbiting?", options:["Al-Nur 24","Al-Ahzab 33","Al-Hujurat 49:11-12","Al-Hashr 59"], answer:2, ref:"49:11-12"},
  {q:"Which surah declares: ‘We sent a Messenger to every people…’?", options:["Al-Nahl 16:36","Fatir 35:24","Both A and B","Al-Anbiya 21:25"], answer:2, ref:"16:36; 35:24"},
  {q:"Which surah states: ‘And of His signs is that He created for you spouses that you may find tranquillity in them’?", options:["Al-Ahzab 33:35","Ar-Rum 30:21","An-Nisa 4:1","Al-Hujurat 49:13"], answer:1, ref:"30:21"},
  {q:"Which surah promises believers ‘He will most surely make them Successors in the earth’ (Ahmadiyya emphasis on Khilafat)?", options:["Ash-Shura 42:38","Al-Nur 24:55","Al-Hajj 22:41","Al-Fath 48:29"], answer:1, ref:"24:55"},
  {q:"Which surah contains ‘If you love Allah, follow me; Allah will love you…’?", options:["Al-Imran 3:31","Al-Ahzab 33:21","Muhammad 47:33","Al-Hashr 59:7"], answer:0, ref:"3:31"},
  {q:"Which surah begins with ‘Blessed is He in Whose hand is the Kingdom’?", options:["Al-Mulk 67:1","Al-Furqan 25:1","Both A and B","Al-Isra 17:1"], answer:0, ref:"67:1"},
  {q:"Which surah contains the prayer of Solomon for a unique kingdom?", options:["An-Naml 27:19","Saba’ 34:12","Sad 38:35","Al-Ahzab 33:27"], answer:2, ref:"38:35"},
  {q:"Which surah refers to Adam being taught the names of all things?", options:["Al-A‘raf 7:19","Al-Baqarah 2:31","Al-Hijr 15:28","Ta-Ha 20:115"], answer:1, ref:"2:31"},
  {q:"Which surah contains ‘And despair not of the mercy of Allah’?", options:["Al-Zumar 39:53","Al-Shura 42:25","Al-Furqan 25:70","Al-Taghabun 64:14"], answer:0, ref:"39:53"},
  {q:"Which surah contains the command to verify news brought by a wicked person (tabayyun)?", options:["Al-Nur 24:15","Al-Ahzab 33:70","Al-Hujurat 49:6","Al-Mumtahanah 60:10"], answer:2, ref:"49:6"},
  {q:"Which surah contains the verse ‘To you your religion and to me mine’?", options:["Al-Kafirun 109:6","Al-Baqarah 2:256","Yunus 10:41","Al-An‘am 6:108"], answer:0, ref:"109:6"},
  {q:"Which surah mentions honey and its healing properties?", options:["Al-Nahl 16:69","Al-Rahman 55:68","Al-Waqi‘ah 56:68","Abasa 80:24"], answer:0, ref:"16:69"},
  {q:"Which surah states that Allah created the heavens and earth in six ‘days’ (periods)?", options:["Al-A‘raf 7:54","Yunus 10:3","Hud 11:7","All of the above"], answer:3, ref:""},
  {q:"Which surah contains the barrier of iron built by Dhu’l-Qarnayn?", options:["Maryam 19","Al-Kahf 18:96","Al-Anbiya 21","Al-Qasas 28"], answer:1, ref:"18:96"},
  {q:"Which surah includes the law of equitable retaliation (qisas): ‘life for life…’?", options:["Al-Ma’idah 5:45","Al-Baqarah 2:178","Both A and B","An-Nisa 4:92"], answer:2, ref:"5:45; 2:178"},
  {q:"Which surah explicitly allows fighting only in self-defence when persecuted (Ahmadiyya emphasis)?", options:["Al-Baqarah 2:190","Al-Hajj 22:39-40","Al-Taubah 9:36","Muhammad 47:4"], answer:1, ref:"22:39-40"},
  {q:"According to Ahmadiyya understanding, which verse indicates God gives glad tidings to the righteous in this life?", options:["Yunus 10:64","Al-Ahzab 33:40","Al-Ma’idah 5:3","Al-Shura 42:51"], answer:0, ref:"10:64"},
  {q:"Which surah declares the Prophet Muhammad (sa) to be ‘a mercy for all peoples’?", options:["Al-Ahzab 33:56","Al-Anbiya 21:107","Al-Fath 48:29","Al-Qalam 68:4"], answer:1, ref:"21:107"},
  {q:"Which surah is often called the ‘Heart of the Qur’an’?", options:["Ya-Sin","Ar-Rahman","Al-Mulk","Al-Qadr"], answer:0, ref:"36"},
  {q:"Which surah is named after the Prophet Hud (as)?", options:["Hud","Nuh","Ibrahim","Yunus"], answer:0, ref:"11"},
  {q:"Which surah is named after the Prophet Jonah (Yunus)?", options:["Yunus","Yusuf","Hud","Al-Anbiya"], answer:0, ref:"10"},
  {q:"Which surah is named after the Prophet Noah (Nuh)?", options:["Nuh","Hud","Yunus","Ibrahim"], answer:0, ref:"71"},
  {q:"Which surah is named after the Prophet Abraham (Ibrahim)?", options:["Ibrahim","Hud","Maryam","Yunus"], answer:0, ref:"14"},
  {q:"Which surah is named after the Prophet Muhammad (sa)?", options:["Muhammad","Al-Ahzab","As-Saff","Al-Fath"], answer:0, ref:"47"},
  {q:"Which surah begins with the disjointed letters ‘Ta Ha’?", options:["Ta-Ha","Ya-Sin","Sad","Maryam"], answer:0, ref:"20:1"},
  {q:"Which surah recounts the meeting of Prophet Moses (as) with Khidr?", options:["Al-Kahf","Taha","Al-A‘raf","Ash-Shu‘ara"], answer:0, ref:"18:60-82"},
  {q:"Which surah narrates the story of the Queen of Sheba (Bilqis) and the hoopoe?", options:["An-Naml","Saba","Al-Qasas","Hud"], answer:0, ref:"27:22-44"},
  {q:"Which surah records Prophet Zakariya (as) praying for a righteous son?", options:["Maryam","Al-Imran","Al-Anbiya","Al-Ahzab"], answer:0, ref:"19:2-15"},
  {q:"Which surah contains the supplication ‘My Lord, increase me in knowledge’?", options:["Ta-Ha","Al-Baqarah","Al-Qalam","Ash-Sharh"], answer:0, ref:"20:114"},
  {q:"Which surah repeats the assurance ‘Indeed, with hardship comes ease’?", options:["Ash-Sharh","Ad-Duha","Al-Inshiqaq","Al-Balad"], answer:0, ref:"94:5-6"},
  {q:"Which surah tells the parable of the owners of the garden who planned to withhold charity?", options:["Al-Qalam","Al-Ma‘arij","Al-Haqqah","At-Takwir"], answer:0, ref:"68:17-33"},
  {q:"Which surah preserves the wise counsel of Luqman to his son?", options:["Luqman","Yunus","Ghafir","Al-Hujurat"], answer:0, ref:"31:13-19"},
  {q:"Which surah declares that Allah does not change the condition of a people until they change what is in themselves?", options:["Ar-Ra‘d","Yunus","Al-An‘am","Ash-Shura"], answer:0, ref:"13:11"},
  {q:"Which surah urges believers to hold fast, all together, to the rope of Allah?", options:["Al-Imran","Al-Anfal","Al-Hadid","Al-Jathiyah"], answer:0, ref:"3:103"},
  {q:"Which surah contains the verse of Mubahala with the Christians of Najran?", options:["Al-Imran","Al-Ma’idah","Maryam","Al-Ankabut"], answer:0, ref:"3:61"},
  {q:"Which surah conveys the divine promise ‘Call upon Me; I will respond to you’?", options:["Ghafir","Al-Baqarah","Fatir","Az-Zumar"], answer:0, ref:"40:60"},
  {q:"Which surah reflects on the signs in the creation of the heavens and the earth for people of understanding?", options:["Al-Imran","Al-Rum","Fatir","Az-Zukhruf"], answer:0, ref:"3:190"},
  {q:"Which surah instructs believers to return a greeting with one better or equal to it?", options:["An-Nisa","Al-Hujurat","Al-Mumtahanah","At-Tawbah"], answer:0, ref:"4:86"},
  {q:"Which surah prescribes fasting for believers as it was prescribed for those before them?", options:["Al-Baqarah","Al-Imran","An-Nisa","Al-Ma’idah"], answer:0, ref:"2:183"},
  {q:"Which surah states that pilgrimage to the House is a duty owed to Allah by people?", options:["Al-Imran","Al-Hajj","Ibrahim","Al-Ma’idah"], answer:0, ref:"3:97"},
  {q:"Which surah declares Safa and Marwah to be among the symbols of Allah?", options:["Al-Baqarah","Al-Nisa","Al-A‘raf","Al-Jumu‘ah"], answer:0, ref:"2:158"},
  {q:"Which surah commands believers to send blessings upon the Prophet Muhammad (sa)?", options:["Al-Ahzab","Al-Hujurat","Al-Fath","Al-Ma‘un"], answer:0, ref:"33:56"},
  {q:"Which surah instructs the faithful not to enter the Prophet’s houses without permission?", options:["Al-Ahzab","An-Nur","Al-Mujadilah","Al-Tahrim"], answer:0, ref:"33:53"},
  {q:"Which surah narrates Prophet Abraham (as) breaking the idols of his people?", options:["Al-Anbiya","Al-An‘am","As-Saffat","Al-Qasas"], answer:0, ref:"21:51-70"},
  {q:"Which surah recounts the persecution of the People of the Trench (Ashab al-Ukhdud)?", options:["Al-Buruj","Al-Ghashiyah","Al-Balad","Al-Fajr"], answer:0, ref:"85:4-9"},
  {q:"Which surah mentions Harut and Marut teaching people only after warning them?", options:["Al-Baqarah","An-Nisa","Al-A‘raf","Yunus"], answer:0, ref:"2:102"},
  {q:"Which surah opens with the reference to the Prophet’s Night Journey from Masjid al-Haram to Masjid al-Aqsa?", options:["Al-Isra","Al-Qamar","Al-Ma‘arij","Al-Inshiqaq"], answer:0, ref:"17:1"},
  {q:"Which surah begins with the command, ‘Glorify the name of your Lord, the Most High’?", options:["Al-A‘la","Al-Ghashiyah","An-Nazi‘at","Al-Fajr"], answer:0, ref:"87:1"},
  {q:"Which surah opens by asking, ‘Has there not come upon man a period of time when he was not a thing mentioned?’", options:["Al-Insan","Al-Muddaththir","Al-Infitar","At-Tariq"], answer:0, ref:"76:1"},
  {q:"Which surah warns, ‘Woe to every slanderer, backbiter’?", options:["Al-Humazah","Al-Ma‘un","At-Takathur","Al-Fil"], answer:0, ref:"104:1"},
  {q:"Which surah proclaims, ‘The Striking Calamity! What is the Striking Calamity?’", options:["Al-Qari‘ah","Al-Zalzalah","Al-Bayyinah","Al-‘Adiyat"], answer:0, ref:"101:1-2"},
  {q:"Which surah opens with ‘Competition in worldly increase diverts you’?", options:["At-Takathur","Al-‘Asr","Al-Humazah","Ad-Duha"], answer:0, ref:"102:1"},
  {q:"Which surah begins with the oath ‘By the chargers that run, panting’?", options:["Al-‘Adiyat","Az-Zalzalah","Al-Qari‘ah","Al-Humazah"], answer:0, ref:"100:1"},
  {q:"Which surah starts with ‘When the sun is folded up’?", options:["At-Takwir","Al-Infitar","Al-Inshiqaq","Al-Ghashiyah"], answer:0, ref:"81:1"},
  {q:"Which surah opens with ‘When the sky is cleft asunder’?", options:["Al-Infitar","At-Takwir","Al-Inshiqaq","Al-Zilzal"], answer:0, ref:"82:1"},
  {q:"Which surah begins with ‘When the earth is shaken with its final earthquake’?", options:["Az-Zalzalah","Al-Qari‘ah","Al-‘Adiyat","Al-Inshiqaq"], answer:0, ref:"99:1"},
  {q:"Which surah contains the reminder ‘So remember Me; I will remember you’?", options:["Al-Baqarah","Al-Imran","An-Nisa","Al-Ma’idah"], answer:0, ref:"2:152"},
  {q:"Which surah assures that ‘Whoever puts his trust in Allah—He is sufficient for him’?", options:["At-Talaq","An-Nur","Al-Hadid","Al-Jumu‘ah"], answer:0, ref:"65:3"},
  {q:"Which surah states, ‘Verily, in the remembrance of Allah do hearts find rest’?", options:["Ar-Ra‘d","Al-An‘am","Al-Mu’minun","Az-Zumar"], answer:0, ref:"13:28"},
  {q:"Which surah observes that Allah created pairs of all things?", options:["Ya-Sin","Az-Zumar","Al-Mulk","Al-Mursalat"], answer:0, ref:"36:36"},
  {q:"Which surah proclaims, ‘Truth has come and falsehood has vanished’?", options:["Al-Isra","Yunus","Al-Furqan","Sad"], answer:0, ref:"17:81"},
  {q:"Which surah directs believers to ‘lower to them the wing of humility out of mercy’ regarding parents?", options:["Al-Isra","Luqman","An-Nisa","Al-Ankabut"], answer:0, ref:"17:24"},
  {q:"Which surah relates Allah’s command to Moses (as), ‘Take off your shoes; you are in the sacred valley of Tuwa’?", options:["Ta-Ha","An-Nazi‘at","Al-Qasas","Al-A‘raf"], answer:0, ref:"20:12"},
  {q:"Which surah describes Pharaoh’s magicians falling in prostration after witnessing Moses’ sign?", options:["Al-A‘raf","Ta-Ha","Ash-Shu‘ara","Al-Qasas"], answer:0, ref:"7:120-126"},
  {q:"Which surah teaches that whoever saves one life, it is as if they saved all mankind?", options:["Al-Ma’idah","Al-Baqarah","An-Nisa","Al-Hajj"], answer:0, ref:"5:32"},
  {q:"Which surah opens by declaring, ‘Successful indeed are the believers’?", options:["Al-Mu’minun","Al-Hujurat","Al-Hadid","As-Saff"], answer:0, ref:"23:1-11"},
  {q:"Which surah praises those whom neither trade nor sale distract from the remembrance of Allah?", options:["An-Nur","Al-Jumu‘ah","Al-Hadid","At-Tawbah"], answer:0, ref:"24:37"},
  {q:"Which surah commands believers to stand firm for justice even against themselves or their relatives?", options:["An-Nisa","Al-Ma’idah","Al-Hajj","Al-Fath"], answer:0, ref:"4:135"}
];
